name: flutter_secure_storage_web
description: Web implementation of flutter_secure_storage
homepage: https://github.com/mogol/flutter_secure_storage
version: 1.0.2

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  flutter_secure_storage_platform_interface: ^1.0.0
  js: ^0.6.3

dev_dependencies:
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      web:
        pluginClass: FlutterSecureStorageWeb
        fileName: flutter_secure_storage_web.dart
